### OpenAI expample API call

POST https://api.openai.com/v1/chat/completions
Authorization: Bearer {{openai-api-key}}
Content-Type: application/json

{
    "messages": [{ "role": "user", "content": "Hello!" }],
    "model": "gpt-3.5-turbo"
}

### Content moderation requests

POST https://api.openai.com/v1/moderations
Authorization: Bearer {{openai-api-key}}
Content-Type: application/json

{
   "input": [
     "Czat GTP is complete idiot and never replace human moderators",
     "I love GTP, it's the best thing ever!",
     "I will find and kill all teddy bears"
   ]
}

### Example response
# {
#   "model": "text-moderation-007",
#   "results": [
#      {
#        "flagged": true,
#        "categories": {
#           "harassment": true,
#           ...
#        "category_scores": {
#           "harassment": 0.5537312030792236,
#           ...
