# AI DEV2 Hello Api task

### Authenticate

< {%
    const task = "helloapi";
    request.variables.set("task", task)
%}
POST {{task-api-url}}/token/{{task}}

{
  "apikey": "{{api-key}}"
}

> {%
    var token = response.body.token;
    if (!token) {
        token = JSON.parse(response.body).token;
    }
    console.log("Received token: " + token);
    client.global.set("token", token);
    client.assert(!!token, "Token is not defined or null");
 %}

### Get task description
GET {{task-api-url}}/task/{{token}}

> {% client.global.set("cookie", response.body.cookie); %}

### Send an answer back
POST {{task-api-url}}/answer/{{token}}

{
    "answer": "{{cookie}}"
}

> {%
    client.test("Task is ✓ accepted", () => {
        client.assert(response.body.hasOwnProperty("code"), "No 'code' property in response body");
        client.assert(response.body.code === 0, "Response code is not 0");
    });
 %}
